# Generated by Django 3.1.4 on 2020-12-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
