# Generated by Django 3.1.4 on 2020-12-18 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201218_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name=1200)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itme_comment', to='auctions.list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
