# Generated by Django 3.1.4 on 2020-12-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
