# Generated by Django 3.1.4 on 2020-12-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201218_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='WahchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itme_watch_list', to='auctions.list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watch_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
