# Generated by Django 3.1.4 on 2020-12-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wahchlist_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wahchlist',
            name='watch_list',
        ),
    ]
