# Generated by Django 3.1.4 on 2020-12-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
