# Generated by Django 3.1.4 on 2020-12-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
